//
//  PlaceDataSource.swift
//  VisitBogor
//
//  Created by Ishaq Fikri Taufik on 17/05/20.
//  Copyright © 2020 Dicoding Indonesia. All rights reserved.
//

import UIKit
var places: [PlaceAttribute] = [
    PlaceAttribute(photo: UIImage(named: "Botani1")!, name: "Bogor Botanical Garden", desc: "The Bogor Botanical Gardens (Indonesian: Kebun Raya Bogor) is a botanical garden located in Bogor, Indonesia, 60 km south of central Jakarta. It is currently operated by Indonesian Institute of Sciences (Indonesian: Lembaga Ilmu Pengetahuan Indonesia or LIPI). The Garden is located in the city center and adjoin the presidential palace compound of Istana Bogor. It covers an area of 87 hectares (210 acres) and contains 13,983 different kinds of trees and plants of various origin. The geographic position of Bogor means it rains almost daily, even in the dry season. This makes the Garden an advantageous location for the cultivation of tropical plants."),
    PlaceAttribute(photo: UIImage(named: "JungeLand1")!, name: "JungleLand Adventure Theme", desc: "Straightforward theme park featuring classic rides, including a ferris wheel & bumper cars. it seems like dufan in jakarta, this place is for you wanna have a good times with your family, girlsfirend or even your with your friends, Jungle Land close to Jagorawi highway, you have to exit on sentul on high way, only 40km from jakarta"),
    PlaceAttribute(photo: UIImage(named: "TheJungle1")!, name: "The Jungle Waterpark", desc: "Amusement park featuring water slides, a wave pool & other attractions amid lush landscaping. if you like to swim it can be the best recomendation, because The Jungle have long swimming pool, while you swimming there is aquarium beside the swimming pool, its onluy"),
    PlaceAttribute(photo: UIImage(named: "Curug1")!, name: "Leuwi Lieuk Waterfall", desc: "Leuwi Lieuk Waterfall is surrounded by pristine environment and lush plants, creating a comfy nuance to the site. In terms of size, it is considered moderate and features strong water discharge. The most noticeable feature is definitely the crystal blue natural pond located beneath it. The pond is surrounded by rocky cliffs and it looks like a private pool! Even the pond is not deep, so everyone is able to swim and play water safely there. Also, the site is quite secluded so it provides a peaceful atmosphere for relaxation."),
    PlaceAttribute(photo: UIImage(named: "Puncak1")!, name: "Puncak Tea Garden", desc: "Puncak, or ‘the peak’, has been considered a favourite among Jakartans for a quick weekend getaway, after Bandung and Bogor, for decades.  We love its clean air, the many tea plantations on either side of the main Puncak road, and the many activities you can do there; from paragliding, tea plantation walking, or just relaxing and admiring the beautiful view. Please be aware that traffic can be horrendous on long weekends, added with the local police’s ‘buka-tutup’ system where the main road is made one way—either upwards or down depending on the time slot— to ease the congestion."),
    PlaceAttribute(photo: UIImage(named: "Zoology1")!, name: "Museum Zoology", desc: "Bogor Zoology Museum is a museum located to the next of the main entrance of the Bogor Botanical Gardens in the city of Bogor, Indonesia.[1] The museum and its laboratory was founded on 1894 by government of Dutch East Indies during the colonial era. It contain one of the largest collection of preserved fauna specimen in Southeast Asia."),
    PlaceAttribute(photo: UIImage(named: "Paragliding1")!, name: "Puncak Tandeng Flight", desc: "Tandem flying is  the ideal way to get a taste of paragliding. Flying with an experienced pilot will make you feel save and comfort. You will get the experience, thrill and excitement of paragliding without having to learn it yourself. You don’t have to learn how to launch or how to control the wing, because what you just need to sit back, enjoy the scenery or even take a few pictures."),
    PlaceAttribute(photo: UIImage(named: "Rafting1")!, name: "River Rafting", desc: "Rafting and white water rafting are recreational outdoor activities which use an inflatable raft to navigate a river or other body of water. This is often done on whitewater or different degrees of rough water. Dealing with risk and the need for teamwork is often a part of the experience"),
    PlaceAttribute(photo: UIImage(named: "MPeta1")!, name: "Museum Peta", desc: "Pembela Tanah Air Museum (PETA Museum) is museum in Bogor, Indonesia. The museum was established to provide a tribute to former soldiers (PETA) for their contributions in establishment the nation. In addition, the museum also gives an overview of Indonesia's independence struggle and preparation to fulfil its independence."),
    PlaceAttribute(photo: UIImage(named: "TamanBungaNusantara1")!, name: "Nusantara Flower Garden", desc: "Taman Bunga Nusantara (TBN) has many diverse collection of beautiful and fresh flowers, ranging from plants to tropical climate as well as for a cold climate, not even just the interest that comes from Indonesia, flowers from all over the world were there. In addition to refresh the eye, we also will get a lot of new insights about the flowers.TBN is located in the Village District Kawung-Luwuk Sukaresmi Cipanas-Cianjur, with total area of ​​35 acres, Garden Flowers Collection presents the beauty and charm and natural flowers arranged beautifully. Founded 10 years ago precisely on September 10, 1995, Indonesia's first display garden is equipped with various collections of plants and flowers are renowned worldwide unique.")
]
